export const clinicalTheme = {
  themeName: 'flat',
  colorPalette: 'light',
  isPanelless: true,
  cssVariables: {
    // Brand Colors (NHS Clinical Teal palette)
    '--sjs2-color-project-brand-600': '#00695c',
    '--sjs2-color-project-brand-700': '#004d40',
    '--sjs2-color-project-brand-800': '#00382e',
    '--sjs2-color-project-brand-400': '#00897b',
    '--sjs2-color-bg-brand-primary': '#00695c',
    '--sjs2-color-bg-brand-primary-dim': '#004d40',
    '--sjs2-color-bg-brand-secondary': 'rgba(0, 105, 92, 0.08)',
    '--sjs2-color-fg-brand-on-primary': '#ffffff',
    '--sjs2-color-fg-brand-primary': '#00695c',
    '--sjs-primary-backcolor': '#00695c',
    '--sjs-primary-backcolor-dark': '#004d40',
    '--sjs-primary-backcolor-light': 'rgba(0, 105, 92, 0.08)',
    '--sjs-primary-forecolor': '#ffffff',

    // Surfaces & Canvas Backgrounds
    '--sjs2-color-utility-surface-survey': 'transparent',
    '--sjs2-color-utility-surface-designer': '#f8fafc',
    '--sjs2-color-bg-basic-primary': '#ffffff',
    '--sjs2-color-bg-basic-secondary': '#ffffff',
    '--sjs2-color-bg-basic-primary-dim': '#f8fafc',
    '--sjs2-color-bg-basic-secondary-dim': '#f1f5f9',
    '--sjs2-color-component-panel-simple-default-bg': 'transparent',
    '--sjs2-color-component-panel-simple-default-border': 'transparent',

    // Text & Foreground (Slate palette matching host app)
    '--sjs2-color-fg-basic-primary': '#0f172a',
    '--sjs2-color-fg-basic-secondary': '#64748b',
    '--sjs2-color-fg-basic-tertiary': '#94a3b8',
    '--sjs2-color-component-question-default-title': '#1e293b',
    '--sjs2-color-component-question-default-description': '#64748b',

    // Borders & Outlines
    '--sjs2-color-border-basic-secondary': '#cbd5e1',
    '--sjs2-color-border-basic-secondary-overlay': '#e2e8f0',
    '--sjs2-color-border-brand-primary': '#00695c',
    '--sjs-border-default': '#cbd5e1',
    '--sjs-border-inside': '#e2e8f0',

    // Formbox Inputs (Consistent 1px borders, rounded-md, teal focus ring)
    '--sjs2-color-component-formbox-default-bg': '#ffffff',
    '--sjs2-color-component-formbox-default-border': '#cbd5e1',
    '--sjs2-color-component-formbox-focused-border': '#00695c',
    '--sjs2-color-component-formbox-hovered-border': '#94a3b8',
    '--sjs2-border-effect-component-formbox-default': '0 0 0 1px #cbd5e1',
    '--sjs2-border-effect-component-formbox-focused': '0 0 0 1px #00695c, 0 0 0 3px rgba(0, 105, 92, 0.15)',
    '--sjs2-border-effect-component-formbox-hovered': '0 0 0 1px #94a3b8',

    // Radii (6px = rounded-md)
    '--sjs2-base-unit-radius': '6px',
    '--sjs2-radius-component-formbox': '6px',
    '--sjs2-radius-form': '6px',
    '--sjs2-radius-form-item': '6px',
    '--sjs-corner-radius': '6px',

    // Spacing & Layout
    '--sjs2-base-unit-spacing': '8px',
    '--sjs-base-unit': '8px',
    '--sjs2-layout-component-survey-header-padding-top': '0px',
    '--sjs2-layout-component-survey-box-padding-top': '0px',
    '--sjs2-layout-component-page-box-gap-vertical': '14px',
    '--sjs2-layout-component-page-content-area-gap-vertical': '14px',
    '--sjs2-layout-component-page-content-area-gap-horizontal': '16px',
    '--sjs2-layout-component-panel-box-gap-vertical': '14px',
    '--sjs2-layout-component-panel-content-area-gap-vertical': '14px',
    '--sjs2-layout-component-panel-content-area-gap-horizontal': '16px',
    '--sjs2-layout-component-panel-nested-box-gap-vertical': '14px',
    '--sjs2-layout-component-panel-nested-content-area-gap-vertical': '14px',
    '--sjs2-layout-component-question-box-gap-vertical': '4px',
    '--sjs2-layout-component-question-box-gap-horizontal': '8px',
    '--sjs2-layout-component-question-header-gap-vertical': '2px',
    '--sjs2-layout-component-question-header-padding-top': '0px',
    '--sjs2-layout-component-question-header-padding-bottom': '0px',
    '--sjs2-layout-component-question-header-padding-left': '0px',
    '--sjs2-layout-component-question-header-padding-right': '0px',
    '--sjs2-layout-component-question-title-padding-top': '0px',
    '--sjs2-layout-component-question-title-padding-bottom': '0px',
    '--sjs2-layout-component-question-description-padding-top': '0px',
    '--sjs2-layout-component-question-description-padding-bottom': '0px',

    // Typography (Open Sans, strictly matching host typography)
    '--sjs2-typography-font-family-text': "'Open Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    '--sjs-font-family': "'Open Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    '--sjs-font-head-family': "'Open Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    '--sjs-font-surveytitle-family': "'Open Sans', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    '--sjs2-typography-font-size-default': '14px',
    '--sjs2-typography-font-size-small': '12px',
    '--sjs2-typography-font-size-medium': '16px',
    '--sjs2-typography-font-size-component-input-content': '14px',
    '--sjs2-typography-font-size-component-question-title': '13.5px',
    '--sjs2-typography-font-size-component-question-description': '12px',
    '--sjs2-typography-font-size-component-panel-title': '15px',
    '--sjs2-typography-font-weight-component-question-title': '600',
    '--sjs2-typography-font-weight-component-panel-title': '700',
    '--sjs2-typography-font-weight-component-action-medium-content': '600',
    '--sjs2-typography-line-height-default': '1.5',
  },
};
